### ISSUE TITLE
How do I read the metrics exported by docker_watch into prometheus?

### ISSUE THREAD

**Issue by abhishekbajpayee** [AlexRudd/docker_watch#3]
I have docker_watch running with port 9100 exposed and prometheus exposed on 9090. How do I read the metrics being exported by docker_watch in prometheus? Sorry I am a bit new to this...

**Comment by alexrudd** [comment]
Hey, you need to configure Prometheus to scrape docker_watch.

Prometheus is configured using a yaml config file, here's the [documentation for that.](https://prometheus.io/docs/operating/configuration/)

An example of a really basic config would be:

```yml
---
global:
  # How often to scrape the targets
  scrape_interval: 30s
  # How long to wait for targets to respond
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'docker_watch'
    static_configs:
        # Address of the docker_watch exporter
      - targets: ['localhost:9100']
        labels:
          group: 'docker_watch'
```

**Comment by abhishekbajpayee** [comment]
I have a docker-compose stack which starts the docker_watch containers along with all other containers but I am still unable to read docker_watch stats in prometheus. Here is my docker-compose.yaml file:

```
version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
      - docker_watch:docker_watch
    depends_on:
      - docker_watch
    networks:
      - back-tier

  docker_watch:
    image: alexrudd/docker_watch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    expose:
      - 9100
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes: 
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
```

and here is my prometheus.yaml file:
```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
        - targets: ['localhost:9090', 'localhost:9100']
```

Any idea why prometheus is still unable to access docker_watch metrics?

**Comment by alexrudd** [comment]
It looks like your Prometheus config is only scraping `localhost:9090` which is the Prometheus server itself.

If you open the Prometheus dashboard and then navigate to the Targets section, you'll see a list of all endpoints which have been configured for scraping and any errors Prometheus had trying to scrape them.

You should be able to add the docker_watch target to your config like so:

```yml
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
        - targets: ['localhost:9090', 'localhost:9100']

  # Here's the bit which is missing:
  - job_name: 'docker_watch'
    static_configs:
        # Address of the docker_watch exporter
      - targets: ['docker_watch:9100']
        labels:
          group: 'docker_watch'
```
